debug: true
dev: true
server:
  public_url: http://localhost:4090/
  client_url: http://localhost:4090/
database:
  type: mysql #sqlite
  mysql:
    host: host.docker.internal
    port: 3306
    username: goapp
    password: goapp
    database: goapp
  sqlite:
    path: database-dev.db

