basePath: /
definitions:
  app.ApiPageResponse:
    properties:
      message:
        type: string
    type: object
  app.ErrResponse:
    properties:
      error:
        description: Errors []string `json:"errors"`
        properties:
          fields:
            additionalProperties: true
            type: object
          message:
            type: string
        type: object
    type: object
  models.RegisterUserForm:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      newsletter:
        type: boolean
      password:
        type: string
      terms_agree:
        type: boolean
    type: object
  models.UserLoginForm:
    properties:
      email:
        type: string
      password:
        type: string
      use_cookie:
        type: boolean
    type: object
info:
  contact:
    email: dev@vocy.de
    name: dev
  description: app server
  title: app server
  version: "1.0"
paths:
  /bl-api/page/v1/user/login:
    post:
      consumes:
      - application/json
      description: login
      parameters:
      - description: Email & Password
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.UserLoginForm'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/app.ErrResponse'
      tags:
      - auth
  /bl-api/page/v1/user/register:
    post:
      consumes:
      - application/json
      description: login
      parameters:
      - description: register informations
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.RegisterUserForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.ApiPageResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/app.ErrResponse'
        "500":
          description: Response JSON
          schema:
            $ref: '#/definitions/app.ErrResponse'
      tags:
      - auth
schemes:
- http
- https
securityDefinitions:
  BEARER:
    description: Type "BEARER" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
